import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, PageNumber,
  AlignmentType, Header, Footer, PageBreak,
} from 'docx';
import PptxGenJS from 'pptxgenjs';

const NAVY = '1A2744';
const AMBER = 'F5A623';

export async function generateDocx(content: Record<string, unknown>, addWatermark: boolean): Promise<Buffer> {
  const planContent = content as { sections?: Array<{ title: string; content: string }> };
  const children: Paragraph[] = [];

  (planContent.sections ?? []).forEach((section, idx) => {
    children.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_1,
        style: 'Heading1',
        run: { color: NAVY, bold: true },
      })
    );
    section.content.split('\n').forEach(para => {
      if (para.trim()) children.push(new Paragraph({ text: para }));
    });
    if (addWatermark && idx % 3 === 2) {
      children.push(new Paragraph({
        children: [new TextRun({ text: 'Generated by AElevate SME Plan AI | aelevate.co.ug', color: 'CCCCCC', size: 20 })],
        alignment: AlignmentType.CENTER,
      }));
    }
    children.push(new Paragraph({ children: [new PageBreak()] }));
  });

  const doc = new Document({
    sections: [{
      headers: {
        default: new Header({
          children: [new Paragraph({
            children: [new TextRun({ text: 'AElevate Business Innovations | Fueling Growth', color: NAVY, bold: true })],
          })],
        }),
      },
      footers: {
        default: new Footer({
          children: [new Paragraph({
            children: [
              new TextRun({ text: 'Confidential — prepared by AElevate Business Innovations. Page ' }),
              new TextRun({ children: [PageNumber.CURRENT] }),
              new TextRun({ text: ' of ' }),
              new TextRun({ children: [PageNumber.TOTAL_PAGES] }),
            ],
          })],
        }),
      },
      children,
    }],
  });

  return Packer.toBuffer(doc);
}

export async function generatePptx(content: Record<string, unknown>): Promise<Buffer> {
  const deckContent = content as { slides?: Array<{ title: string; headline: string; bodyPoints: string[]; speakerNotes?: string }> };
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';

  pptx.defineSlideMaster({
    title: 'AELEVATE_MASTER',
    background: { color: 'FFFFFF' },
    objects: [
      { rect: { x: 0, y: 0, w: '100%', h: 1.2, fill: { color: NAVY } } },
      { rect: { x: 0, y: 1.2, w: '100%', h: 0.08, fill: { color: AMBER } } },
    ],
    slideNumber: { x: 9.3, y: 6.9, color: '6B7A8D', fontSize: 10 },
  });

  (deckContent.slides ?? []).forEach(slide => {
    const s = pptx.addSlide({ masterName: 'AELEVATE_MASTER' });
    s.addText(slide.headline ?? slide.title, {
      x: 0.4, y: 0.15, w: 9.2, h: 0.9,
      fontSize: 24, bold: true, color: 'FFFFFF', fontFace: 'Calibri',
    });
    const points = (slide.bodyPoints ?? []).map(p => ({ text: p, bullet: { color: AMBER }, color: '1C1C1C', fontSize: 16 }));
    if (points.length > 0) {
      s.addText(points, { x: 0.4, y: 1.5, w: 9.2, h: 5, valign: 'top', fontFace: 'Calibri' });
    }
    if (slide.speakerNotes) s.addNotes(slide.speakerNotes);
  });

  return Buffer.from(await pptx.write({ outputType: 'nodebuffer' }) as ArrayBuffer);
}
