name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-node: '20'

      - name: Install and Build Frontend
        # Navigate to the web app folder, install dependencies, and build
        run: |
          npm install
          npm run build
        working-directory: apps/web

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Target the dist folder inside the web app folder
          path: 'apps/web/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
